export enum RouteNames {
  HOME = "HOME",
  EDIT = "EDIT",
  BOOK_EDIT = "BOOK_EDIT",
  BOOK_ADD = "BOOK_ADD",
  AUTHORS = "AUTHORS",
  AUTHORS_EDIT = "AUTHORS_EDIT",
  AUTHOR_EDIT = "AUTHOR_EDIT",
  AUTHOR_ADD = "AUTHOR_ADD",
  SETTINGS = "SETTINGS"
}
